# Example workflow part 2

In this case we only need one more class (at least on subject level). So the Base_project class is a bit unnecessary. But imagine different data types or classes for different analysis and it all makes sense.
We'll now inherit from the class and add the analysis class on top of this:

In [1]:
import numpy as np
from scipy import stats
import os

from Base_project import Base_project

There's one more trick. Remember how we ran `list_subjects` in the `__init__ ` method of Base_project? We're overwriting the `__init__`method in the new class. So that doesn't get called by default, but it would be nice. We can call the `__init__`-method of the superclass (the one we inherit) from like this:

In [2]:
class Subject( Base_project):
    
    def __init__(self,subID):
        super().__init__();
        self.subID = subID;

In [3]:
s = Subject(2);
print( s.subjects)

['s01', 's02', 's03', 's04', 's05', 's06', 's07', 's09', 's10', 's11', 's12', 's13', 's14', 's15']

Looking at the assignment we can already think about a few methods we will need:

In [4]:
class Subject( Base_project):
    
    def __init__(self,subID):
        super().__init__();
        self.subID = subID;
        
    #we will have to load the data
    def load_data(self):
        pass
    
    #we will use a linear regression
    def run_regression(self):
        pass
    
    #we have to convert the sequence of foodIDs into a 
    def convert_seq(self):
        pass
    
    #a function that plots reaction times against ratings
    def plot(self):
        pass

Let's start with the `__init__`-method. It should raise an error if the subject doesn't exist. This information is already in the object thanks to the `super().__init__()` -part. So we can just check like this:

In [5]:
subID = 10
s.subject_exists( subID)

True

and in the init method:

In [6]:
class Subject( Base_project):
    
    def __init__(self,subID):
        super().__init__();
        self.subID = subID;
        if not self.subject_exists(subID):
            raise Exception('No such subject in the directory ' + self.path)

In [7]:
s = Subject(99)

Exception: No such subject in the directory C:/Users/neugebauer/Documents/Python_workshop/toy_data/

okay. The obvious first step is to load the data into the object. The data is in .csv-files. You would now google for a way to read those into python. You could add `numpy` or `pandas` in your search because you know you will use these packages to handle the data. I usually would use pandas for this, but we'll stick to numpy for now.

You will somehow find out that `np.genfromtxt` is probably what you're looking for.

In [8]:
np.genfromtxt?

Signature:
np.genfromtxt(
    ['fname', "dtype=<class 'float'>", "comments='#'", 'delimiter=None', 'skip_header=0', 'skip_footer=0', 'converters=None', 'missing_values=None', 'filling_values=None', 'usecols=None', 'names=None', 'excludelist=None', 'deletechars=None', "replace_space='_'", 'autostrip=False', 'case_sensitive=True', "defaultfmt='f%i'", 'unpack=None', 'usemask=False', 'loose=True', 'invalid_raise=True', 'max_rows=None', "encoding='bytes'"],
)
Docstring:
Load data from a text file, with missing values handled as specified.

Each line past the first `skip_header` lines is split at the `delimiter`
character, and characters following the `comments` character are discarded.

Parameters
----------
fname : file, str, pathlib.Path, list of str, generator
    File, filename, list, or generator to read.  If the filename
    extension is `.gz` or `.bz2`, the file is first decompressed. Note
    that generators must return byte strings in Python 3k.  The strings
    in a list or produced by a generator are treated as lines.
dtype : dtype, optional
    Data type of the resulting array.
    If None, the dtypes will be determined by the contents of each
    column, individually.
comments : str, optional
    The character used to indicate the start of a comment.
    All the characters occurring on a line after a comment are discarded
delimiter : str, int, or sequence, optional
    The string used to separate values.  By default, any consecutive
    whitespaces act as delimiter.  An integer or sequence of integers
    can also be provided as width(s) of each field.
skiprows : int, optional
    `skiprows` was removed in numpy 1.10. Please use `skip_header` instead.
skip_header : int, optional
    The number of lines to skip at the beginning of the file.
skip_footer : int, optional
    The number of lines to skip at the end of the file.
converters : variable, optional
    The set of functions that convert the data of a column to a value.
    The converters can also be used to provide a default value
    for missing data: ``converters = {3: lambda s: float(s or 0)}``.
missing : variable, optional
    `missing` was removed in numpy 1.10. Please use `missing_values`
    instead.
missing_values : variable, optional
    The set of strings corresponding to missing data.
filling_values : variable, optional
    The set of values to be used as default when the data are missing.
usecols : sequence, optional
    Which columns to read, with 0 being the first.  For example,
    ``usecols = (1, 4, 5)`` will extract the 2nd, 5th and 6th columns.
names : {None, True, str, sequence}, optional
    If `names` is True, the field names are read from the first line after
    the first `skip_header` lines.  This line can optionally be proceeded
    by a comment delimiter. If `names` is a sequence or a single-string of
    comma-separated names, the names will be used to define the field names
    in a structured dtype. If `names` is None, the names of the dtype
    fields will be used, if any.
excludelist : sequence, optional
    A list of names to exclude. This list is appended to the default list
    ['return','file','print']. Excluded names are appended an underscore:
    for example, `file` would become `file_`.
deletechars : str, optional
    A string combining invalid characters that must be deleted from the
    names.
defaultfmt : str, optional
    A format used to define default field names, such as "f%i" or "f_%02i".
autostrip : bool, optional
    Whether to automatically strip white spaces from the variables.
replace_space : char, optional
    Character(s) used in replacement of white spaces in the variables
    names. By default, use a '_'.
case_sensitive : {True, False, 'upper', 'lower'}, optional
    If True, field names are case sensitive.
    If False or 'upper', field names are converted to upper case.
    If 'lower', field names are converted to lower case.
unpack : bool, optional
    If True, the returned array is transposed, so that arguments may be
    unpacked using ``x, y, z = loadtxt(...)``
usemask : bool, optional
    If True, return a masked array.
    If False, return a regular array.
loose : bool, optional
    If True, do not raise errors for invalid values.
invalid_raise : bool, optional
    If True, an exception is raised if an inconsistency is detected in the
    number of columns.
    If False, a warning is emitted and the offending lines are skipped.
max_rows : int,  optional
    The maximum number of rows to read. Must not be used with skip_footer
    at the same time.  If given, the value must be at least 1. Default is
    to read the entire file.

    .. versionadded:: 1.10.0
encoding : str, optional
    Encoding used to decode the inputfile. Does not apply when `fname` is
    a file object.  The special value 'bytes' enables backward compatibility
    workarounds that ensure that you receive byte arrays when possible
    and passes latin1 encoded strings to converters. Override this value to
    receive unicode arrays and pass strings as input to converters.  If set
    to None the system default is used. The default value is 'bytes'.

    .. versionadded:: 1.14.0

Returns
-------
out : ndarray
    Data read from the text file. If `usemask` is True, this is a
    masked array.

See Also
--------
numpy.loadtxt : equivalent function when no data is missing.

Notes
-----
* When spaces are used as delimiters, or when no delimiter has been given
  as input, there should not be any missing data between two fields.
* When the variables are named (either by a flexible dtype or with `names`,
  there must not be any header in the file (else a ValueError
  exception is raised).
* Individual values are not stripped of spaces by default.
  When using a custom converter, make sure the function does remove spaces.

References
----------
.. [1] NumPy User Guide, section `I/O with NumPy
       <http://docs.scipy.org/doc/numpy/user/basics.io.genfromtxt.html>`_.

Examples
---------
>>> from io import StringIO
>>> import numpy as np

Comma delimited file with mixed dtype

>>> s = StringIO(u"1,1.3,abcde")
>>> data = np.genfromtxt(s, dtype=[('myint','i8'),('myfloat','f8'),
... ('mystring','S5')], delimiter=",")
>>> data
array((1, 1.3, 'abcde'),
      dtype=[('myint', '<i8'), ('myfloat', '<f8'), ('mystring', '|S5')])

Using dtype = None

>>> s.seek(0) # needed for StringIO example only
>>> data = np.genfromtxt(s, dtype=None,
... names = ['myint','myfloat','mystring'], delimiter=",")
>>> data
array((1, 1.3, 'abcde'),
      dtype=[('myint', '<i8'), ('myfloat', '<f8'), ('mystring', '|S5')])

Specifying dtype and names

>>> s.seek(0)
>>> data = np.genfromtxt(s, dtype="i8,f8,S5",
... names=['myint','myfloat','mystring'], delimiter=",")
>>> data
array((1, 1.3, 'abcde'),
      dtype=[('myint', '<i8'), ('myfloat', '<f8'), ('mystring', '|S5')])

An example with fixed-width columns

>>> s = StringIO(u"11.3abcde")
>>> data = np.genfromtxt(s, dtype=None, names=['intvar','fltvar','strvar'],
...     delimiter=[1,3,5])
>>> data
array((1, 1.3, 'abcde'),
      dtype=[('intvar', '<i8'), ('fltvar', '<f8'), ('strvar', '|S5')])
File:      c:\users\neugebauer\anaconda3\lib\site-packages\numpy\lib\npyio.py
Type:      function

You see that there's a whole lot of options here. In our case the files are comma separated, so let's just try it out in the simplest way:

In [9]:
s = Subject(1);
pth = s. path_to_data(1,'food');
print(pth)

C:/Users/neugebauer/Documents/Python_workshop/toy_data/s01\food_ratings.csv

In [10]:
test = np.genfromtxt(pth, delimiter = ',');
print(test)

[[ 1.  2.]
 [ 2.  9.]
 [ 3.  7.]
 [ 4.  4.]
 [ 5. 18.]
 [ 6.  9.]
 [ 7.  6.]
 [ 8. 13.]
 [ 9. 17.]
 [10.  7.]
 [11. 16.]
 [12.  7.]
 [13. 13.]
 [14.  3.]
 [15.  5.]
 [16. 20.]
 [17. 12.]
 [18.  2.]
 [19.  9.]
 [20. 11.]
 [21. 20.]
 [22. 13.]
 [23.  7.]
 [24.  3.]
 [25.  5.]
 [26. 11.]
 [27. 14.]
 [28. 16.]
 [29.  5.]
 [30.  7.]]

That looks good. In readcion times there are floats and integers, that might be harder...

In [11]:
pth2 = s.path_to_data(1,'RT');

In [12]:
t2 = np.genfromtxt( pth2 );
print(t2)

[nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan]

Yeah, that looks bad. Either, you try to work around it, or you hope the pandas people have done this for you and try again using pandas:

In [23]:
import pandas as pd
t2 = pd.read_csv(pth2);
t2.head()

   29.0  0.3874505638951348
0  19.0            0.484971
1   7.0            0.531008
2  11.0            0.411700
3   7.0            0.256366
4  24.0            0.555504

Unfortunately, this steals the first row and uses it as names for columns. There sure is a way around that:

In [43]:
pd.read_csv?

Signature:
pd.read_csv(
    ['filepath_or_buffer', "sep=','", 'delimiter=None', "header='infer'", 'names=None', 'index_col=None', 'usecols=None', 'squeeze=False', 'prefix=None', 'mangle_dupe_cols=True', 'dtype=None', 'engine=None', 'converters=None', 'true_values=None', 'false_values=None', 'skipinitialspace=False', 'skiprows=None', 'nrows=None', 'na_values=None', 'keep_default_na=True', 'na_filter=True', 'verbose=False', 'skip_blank_lines=True', 'parse_dates=False', 'infer_datetime_format=False', 'keep_date_col=False', 'date_parser=None', 'dayfirst=False', 'iterator=False', 'chunksize=None', "compression='infer'", 'thousands=None', "decimal=b'.'", 'lineterminator=None', 'quotechar=\'"\'', 'quoting=0', 'escapechar=None', 'comment=None', 'encoding=None', 'dialect=None', 'tupleize_cols=None', 'error_bad_lines=True', 'warn_bad_lines=True', 'skipfooter=0', 'doublequote=True', 'delim_whitespace=False', 'low_memory=True', 'memory_map=False', 'float_precision=None'],
)
Docstring:
Read CSV (comma-separated) file into DataFrame

Also supports optionally iterating or breaking of the file
into chunks.

Additional help can be found in the `online docs for IO Tools
<http://pandas.pydata.org/pandas-docs/stable/io.html>`_.

Parameters
----------
filepath_or_buffer : str, pathlib.Path, py._path.local.LocalPath or any \
object with a read() method (such as a file handle or StringIO)
    The string could be a URL. Valid URL schemes include http, ftp, s3, and
    file. For file URLs, a host is expected. For instance, a local file could
    be file://localhost/path/to/table.csv
sep : str, default ','
    Delimiter to use. If sep is None, the C engine cannot automatically detect
    the separator, but the Python parsing engine can, meaning the latter will
    be used and automatically detect the separator by Python's builtin sniffer
    tool, ``csv.Sniffer``. In addition, separators longer than 1 character and
    different from ``'\s+'`` will be interpreted as regular expressions and
    will also force the use of the Python parsing engine. Note that regex
    delimiters are prone to ignoring quoted data. Regex example: ``'\r\t'``
delimiter : str, default ``None``
    Alternative argument name for sep.
delim_whitespace : boolean, default False
    Specifies whether or not whitespace (e.g. ``' '`` or ``'\t'``) will be
    used as the sep. Equivalent to setting ``sep='\s+'``. If this option
    is set to True, nothing should be passed in for the ``delimiter``
    parameter.

    .. versionadded:: 0.18.1 support for the Python parser.

header : int or list of ints, default 'infer'
    Row number(s) to use as the column names, and the start of the
    data.  Default behavior is to infer the column names: if no names
    are passed the behavior is identical to ``header=0`` and column
    names are inferred from the first line of the file, if column
    names are passed explicitly then the behavior is identical to
    ``header=None``. Explicitly pass ``header=0`` to be able to
    replace existing names. The header can be a list of integers that
    specify row locations for a multi-index on the columns
    e.g. [0,1,3]. Intervening rows that are not specified will be
    skipped (e.g. 2 in this example is skipped). Note that this
    parameter ignores commented lines and empty lines if
    ``skip_blank_lines=True``, so header=0 denotes the first line of
    data rather than the first line of the file.
names : array-like, default None
    List of column names to use. If file contains no header row, then you
    should explicitly pass header=None. Duplicates in this list will cause
    a ``UserWarning`` to be issued.
index_col : int or sequence or False, default None
    Column to use as the row labels of the DataFrame. If a sequence is given, a
    MultiIndex is used. If you have a malformed file with delimiters at the end
    of each line, you might consider index_col=False to force pandas to _not_
    use the first column as the index (row names)
usecols : list-like or callable, default None
    Return a subset of the columns. If list-like, all elements must either
    be positional (i.e. integer indices into the document columns) or strings
    that correspond to column names provided either by the user in `names` or
    inferred from the document header row(s). For example, a valid list-like
    `usecols` parameter would be [0, 1, 2] or ['foo', 'bar', 'baz']. Element
    order is ignored, so ``usecols=[0, 1]`` is the same as ``[1, 0]``.
    To instantiate a DataFrame from ``data`` with element order preserved use
    ``pd.read_csv(data, usecols=['foo', 'bar'])[['foo', 'bar']]`` for columns
    in ``['foo', 'bar']`` order or
    ``pd.read_csv(data, usecols=['foo', 'bar'])[['bar', 'foo']]``
    for ``['bar', 'foo']`` order.

    If callable, the callable function will be evaluated against the column
    names, returning names where the callable function evaluates to True. An
    example of a valid callable argument would be ``lambda x: x.upper() in
    ['AAA', 'BBB', 'DDD']``. Using this parameter results in much faster
    parsing time and lower memory usage.
squeeze : boolean, default False
    If the parsed data only contains one column then return a Series
prefix : str, default None
    Prefix to add to column numbers when no header, e.g. 'X' for X0, X1, ...
mangle_dupe_cols : boolean, default True
    Duplicate columns will be specified as 'X', 'X.1', ...'X.N', rather than
    'X'...'X'. Passing in False will cause data to be overwritten if there
    are duplicate names in the columns.
dtype : Type name or dict of column -> type, default None
    Data type for data or columns. E.g. {'a': np.float64, 'b': np.int32}
    Use `str` or `object` together with suitable `na_values` settings
    to preserve and not interpret dtype.
    If converters are specified, they will be applied INSTEAD
    of dtype conversion.
engine : {'c', 'python'}, optional
    Parser engine to use. The C engine is faster while the python engine is
    currently more feature-complete.
converters : dict, default None
    Dict of functions for converting values in certain columns. Keys can either
    be integers or column labels
true_values : list, default None
    Values to consider as True
false_values : list, default None
    Values to consider as False
skipinitialspace : boolean, default False
    Skip spaces after delimiter.
skiprows : list-like or integer or callable, default None
    Line numbers to skip (0-indexed) or number of lines to skip (int)
    at the start of the file.

    If callable, the callable function will be evaluated against the row
    indices, returning True if the row should be skipped and False otherwise.
    An example of a valid callable argument would be ``lambda x: x in [0, 2]``.
skipfooter : int, default 0
    Number of lines at bottom of file to skip (Unsupported with engine='c')
nrows : int, default None
    Number of rows of file to read. Useful for reading pieces of large files
na_values : scalar, str, list-like, or dict, default None
    Additional strings to recognize as NA/NaN. If dict passed, specific
    per-column NA values.  By default the following values are interpreted as
    NaN: '', '#N/A', '#N/A N/A', '#NA', '-1.#IND', '-1.#QNAN', '-NaN', '-nan',
    '1.#IND', '1.#QNAN', 'N/A', 'NA', 'NULL', 'NaN', 'n/a', 'nan',
    'null'.
keep_default_na : bool, default True
    Whether or not to include the default NaN values when parsing the data.
    Depending on whether `na_values` is passed in, the behavior is as follows:

    * If `keep_default_na` is True, and `na_values` are specified, `na_values`
      is appended to the default NaN values used for parsing.
    * If `keep_default_na` is True, and `na_values` are not specified, only
      the default NaN values are used for parsing.
    * If `keep_default_na` is False, and `na_values` are specified, only
      the NaN values specified `na_values` are used for parsing.
    * If `keep_default_na` is False, and `na_values` are not specified, no
      strings will be parsed as NaN.

    Note that if `na_filter` is passed in as False, the `keep_default_na` and
    `na_values` parameters will be ignored.
na_filter : boolean, default True
    Detect missing value markers (empty strings and the value of na_values). In
    data without any NAs, passing na_filter=False can improve the performance
    of reading a large file
verbose : boolean, default False
    Indicate number of NA values placed in non-numeric columns
skip_blank_lines : boolean, default True
    If True, skip over blank lines rather than interpreting as NaN values
parse_dates : boolean or list of ints or names or list of lists or dict, default False

    * boolean. If True -> try parsing the index.
    * list of ints or names. e.g. If [1, 2, 3] -> try parsing columns 1, 2, 3
      each as a separate date column.
    * list of lists. e.g.  If [[1, 3]] -> combine columns 1 and 3 and parse as
      a single date column.
    * dict, e.g. {'foo' : [1, 3]} -> parse columns 1, 3 as date and call result
      'foo'

    If a column or index contains an unparseable date, the entire column or
    index will be returned unaltered as an object data type. For non-standard
    datetime parsing, use ``pd.to_datetime`` after ``pd.read_csv``

    Note: A fast-path exists for iso8601-formatted dates.
infer_datetime_format : boolean, default False
    If True and `parse_dates` is enabled, pandas will attempt to infer the
    format of the datetime strings in the columns, and if it can be inferred,
    switch to a faster method of parsing them. In some cases this can increase
    the parsing speed by 5-10x.
keep_date_col : boolean, default False
    If True and `parse_dates` specifies combining multiple columns then
    keep the original columns.
date_parser : function, default None
    Function to use for converting a sequence of string columns to an array of
    datetime instances. The default uses ``dateutil.parser.parser`` to do the
    conversion. Pandas will try to call `date_parser` in three different ways,
    advancing to the next if an exception occurs: 1) Pass one or more arrays
    (as defined by `parse_dates`) as arguments; 2) concatenate (row-wise) the
    string values from the columns defined by `parse_dates` into a single array
    and pass that; and 3) call `date_parser` once for each row using one or
    more strings (corresponding to the columns defined by `parse_dates`) as
    arguments.
dayfirst : boolean, default False
    DD/MM format dates, international and European format
iterator : boolean, default False
    Return TextFileReader object for iteration or getting chunks with
    ``get_chunk()``.
chunksize : int, default None
    Return TextFileReader object for iteration.
    See the `IO Tools docs
    <http://pandas.pydata.org/pandas-docs/stable/io.html#io-chunking>`_
    for more information on ``iterator`` and ``chunksize``.
compression : {'infer', 'gzip', 'bz2', 'zip', 'xz', None}, default 'infer'
    For on-the-fly decompression of on-disk data. If 'infer' and
    `filepath_or_buffer` is path-like, then detect compression from the
    following extensions: '.gz', '.bz2', '.zip', or '.xz' (otherwise no
    decompression). If using 'zip', the ZIP file must contain only one data
    file to be read in. Set to None for no decompression.

    .. versionadded:: 0.18.1 support for 'zip' and 'xz' compression.

thousands : str, default None
    Thousands separator
decimal : str, default '.'
    Character to recognize as decimal point (e.g. use ',' for European data).
float_precision : string, default None
    Specifies which converter the C engine should use for floating-point
    values. The options are `None` for the ordinary converter,
    `high` for the high-precision converter, and `round_trip` for the
    round-trip converter.
lineterminator : str (length 1), default None
    Character to break file into lines. Only valid with C parser.
quotechar : str (length 1), optional
    The character used to denote the start and end of a quoted item. Quoted
    items can include the delimiter and it will be ignored.
quoting : int or csv.QUOTE_* instance, default 0
    Control field quoting behavior per ``csv.QUOTE_*`` constants. Use one of
    QUOTE_MINIMAL (0), QUOTE_ALL (1), QUOTE_NONNUMERIC (2) or QUOTE_NONE (3).
doublequote : boolean, default ``True``
   When quotechar is specified and quoting is not ``QUOTE_NONE``, indicate
   whether or not to interpret two consecutive quotechar elements INSIDE a
   field as a single ``quotechar`` element.
escapechar : str (length 1), default None
    One-character string used to escape delimiter when quoting is QUOTE_NONE.
comment : str, default None
    Indicates remainder of line should not be parsed. If found at the beginning
    of a line, the line will be ignored altogether. This parameter must be a
    single character. Like empty lines (as long as ``skip_blank_lines=True``),
    fully commented lines are ignored by the parameter `header` but not by
    `skiprows`. For example, if ``comment='#'``, parsing
    ``#empty\na,b,c\n1,2,3`` with ``header=0`` will result in 'a,b,c' being
    treated as the header.
encoding : str, default None
    Encoding to use for UTF when reading/writing (ex. 'utf-8'). `List of Python
    standard encodings
    <https://docs.python.org/3/library/codecs.html#standard-encodings>`_
dialect : str or csv.Dialect instance, default None
    If provided, this parameter will override values (default or not) for the
    following parameters: `delimiter`, `doublequote`, `escapechar`,
    `skipinitialspace`, `quotechar`, and `quoting`. If it is necessary to
    override values, a ParserWarning will be issued. See csv.Dialect
    documentation for more details.
tupleize_cols : boolean, default False
    .. deprecated:: 0.21.0
       This argument will be removed and will always convert to MultiIndex

    Leave a list of tuples on columns as is (default is to convert to
    a MultiIndex on the columns)
error_bad_lines : boolean, default True
    Lines with too many fields (e.g. a csv line with too many commas) will by
    default cause an exception to be raised, and no DataFrame will be returned.
    If False, then these "bad lines" will dropped from the DataFrame that is
    returned.
warn_bad_lines : boolean, default True
    If error_bad_lines is False, and warn_bad_lines is True, a warning for each
    "bad line" will be output.
low_memory : boolean, default True
    Internally process the file in chunks, resulting in lower memory use
    while parsing, but possibly mixed type inference.  To ensure no mixed
    types either set False, or specify the type with the `dtype` parameter.
    Note that the entire file is read into a single DataFrame regardless,
    use the `chunksize` or `iterator` parameter to return the data in chunks.
    (Only valid with C parser)
memory_map : boolean, default False
    If a filepath is provided for `filepath_or_buffer`, map the file object
    directly onto memory and access the data directly from there. Using this
    option can improve performance because there is no longer any I/O overhead.

Returns
-------
result : DataFrame or TextParser
File:      c:\users\neugebauer\anaconda3\lib\site-packages\pandas\io\parsers.py
Type:      function

`header` could be worth a try. Usually passing `None` works in cases like this:

In [45]:
import pandas as pd
t2 = pd.read_csv(pth2, header = None);
t2.head()

      0         1
0  29.0  0.387451
1  19.0  0.484971
2   7.0  0.531008
3  11.0  0.411700
4   7.0  0.256366

Thanks, pandas people! We won't use pandas for the analysis, but for input/output is usually way easier to use than numpy. Let's have a look at the type of what we got back

In [16]:
print(type(t2))

<class 'pandas.core.frame.DataFrame'>

okay, a DataFrame. As usual, we can use `np.array` to convert other objects into arrays. Or we use the fact, that pandas is a wrapper around numpy and we can get the `values` attribute, which is the raw array:

In [24]:
t2_array = t2.values;
print(type(t2_array));
print(t2_array[:10,:])

<class 'numpy.ndarray'>
[[19.          0.48497081]
 [ 7.          0.53100802]
 [11.          0.41169963]
 [ 7.          0.25636602]
 [24.          0.55550408]
 [23.          1.04104525]
 [21.          0.41044408]
 [ 1.          0.4713283 ]
 [ 1.          0.73012736]
 [14.          0.41438151]]

that is a good approach. So for all of the files we will first read them using pandas and then convert them to np.arrays:

In [18]:
def read_data(subject, typ):
    path = subject.path_to_data( subject.subID, typ);
    df = pd.read_csv( path );
    return df.values

In [21]:
array= read_data( s, 'food');
print(array)

[[ 2  9]
 [ 3  7]
 [ 4  4]
 [ 5 18]
 [ 6  9]
 [ 7  6]
 [ 8 13]
 [ 9 17]
 [10  7]
 [11 16]
 [12  7]
 [13 13]
 [14  3]
 [15  5]
 [16 20]
 [17 12]
 [18  2]
 [19  9]
 [20 11]
 [21 20]
 [22 13]
 [23  7]
 [24  3]
 [25  5]
 [26 11]
 [27 14]
 [28 16]
 [29  5]
 [30  7]]

A few google searches and a bit of coding and we might arrive here:

In [46]:
def load_data(subject):
    
    load_rating(subject);
    load_RT(subject);
    
def load_rating(subject):
    
    path = subjects.path_to_data( subjects.subID, 'food' );
    subject.rating = pd.read_csv(path, header = None ).values;
    
def load_RT(subject):
    path = subject.path_to_data( subjects.subID, 'RT' );
    dummy = pd.read_csv( path , header = None ).values;
    subject.RT = dummy[:,1];
    subject.seq = dummy[:,0];

We could also load the rating_seq, but to convert this from the ratings and the sequence is part of the assigment, so we don't. In the class:

In [47]:
class Subject( Base_project):
    
    def __init__(self,subID):
        super().__init__();
        self.subID = subID;
        
    #we will have to load the data
    def load_data(self):
        self.load_rating();
        self.load_RT();
        
    def load_rating(self):
        path = self.path_to_data( self.subID, 'food' );
        self.rating = pd.read_csv(path, header = None).values;
    
    def load_RT(self):
        path = self.path_to_data( self.subID, 'RT' );
        dummy = pd.read_csv( path, header = None ).values;
        self.RT = dummy[:,1]; # second column are RTs
        self.seq = dummy[:,0]; # first column is sequence
    
    #we will use a linear regression
    def run_regression(self):
        pass
    
    #we have to convert the sequence of foodIDs into a 
    def convert_seq(self):
        pass
    
    #a function that plots reaction times against ratings
    def plot(self):
        pass

In [48]:
s = Subject(1);
s.load_data();
print(s.rating)

[[ 1  2]
 [ 2  9]
 [ 3  7]
 [ 4  4]
 [ 5 18]
 [ 6  9]
 [ 7  6]
 [ 8 13]
 [ 9 17]
 [10  7]
 [11 16]
 [12  7]
 [13 13]
 [14  3]
 [15  5]
 [16 20]
 [17 12]
 [18  2]
 [19  9]
 [20 11]
 [21 20]
 [22 13]
 [23  7]
 [24  3]
 [25  5]
 [26 11]
 [27 14]
 [28 16]
 [29  5]
 [30  7]]

Works fine until here. Trying to convert the sequence of food_ids into a sequence of ratings. You could do something like this:

In [49]:
seq = s.seq;
rate = s.rating

In [55]:
rate_seq = np.zeros(seq.shape)
for i,s in enumerate(seq):
    rating = rate[rate[:,0] == s,1]
    
    rate_seq[i] = rating;
print(rate_seq)

[ 5.  9.  6. 16.  6.  3.  7. 20.  2.  2.  3.  6. 11.  6. 18.  7.  9. 11.
 20. 17. 17.  4. 13.  7.  2. 18. 13.  4.  2.  5. 13.  9. 16. 12.  5. 18.
 13. 13.  9.  5.  7.  4. 13. 14.  7. 20. 17.  7.  7.  7.  3. 16.  7. 16.
  9.  3. 13. 16.  9.  3.  9. 11.  5.  4. 16.  7. 13.  6. 17. 11.  5.  7.
 12.  5.  7.  7.  7.  9.  2. 14. 12.  3. 20.  7.  9. 11.  3.  4.  7.  5.
  3. 20. 12.  9. 11. 18.  5. 13.  9.  7.  7.  2. 11. 13.  7.  7. 20. 20.
 14.  7.  5.  2.  7. 12. 16. 17. 16.  7.  7.  9. 13. 13.  5. 11.  3. 16.
  5.  2.  3.  2.  5. 11.  5. 13.  2. 16.  9.  5. 14.  9. 20.  9. 20.  7.
 13. 14. 11. 18. 13. 20.]

In [62]:
#but probably list comprehension is quicker
rate_seq = np.array( [rate[ rate[:,0] == s, 1] for s in seq ]);

In [64]:
def convert_seq(subject):
    subject.rate_seq = np.array( [ rate[ rate[:,0] == s, 1] for s in subject.seq ] );

and in the class:

In [ ]:
class Subject( Base_project):
    
    def __init__(self,subID):
        super().__init__();
        self.subID = subID;
        
    #we will have to load the data
    def load_data(self):
        self.load_rating();
        self.load_RT();
        
    def load_rating(self):
        path = self.path_to_data( self.subID, 'food' );
        self.rating = pd.read_csv(path, header = None).values;
    
    def load_RT(self):
        path = self.path_to_data( self.subID, 'RT' );
        dummy = pd.read_csv( path, header = None ).values;
        self.RT = dummy[:,1]; # second column are RTs
        self.seq = dummy[:,0]; # first column is sequence
        
    #we have to convert the sequence of foodIDs into a 
    def convert_seq(self):
        self.rate_seq = np.array( [ rate[ rate[:,0] == s, 1] for s in self.seq ] );
    
    #we will use a linear regression
    def run_regression(self):
        pass
    
    #a function that plots reaction times against ratings
    def plot(self):
        pass